<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM haproxy:2.3

RUN apt-get update
RUN apt-get install -y certbot

COPY misc/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
